# Using Libraries in class

- Pedro Mauri Mtz - A01029143

Learning how to use Numpy, Pandas and Matplotlib.

### Libraries:

In [2]:
import os
ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Numpy

In [3]:
array = np.zeros(10).reshape(5, 2)
print(array)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

In [4]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
1
(5,)
5
int64

In [5]:
arr = np.arange(3, 12, 2)
print(arr)

[ 3  5  7  9 11]

In [6]:
arr_random = np.random.rand(10)
print(arr_random)

[0.45869004 0.59012885 0.21507058 0.0867835  0.70364265 0.57205758
 0.67242831 0.138607   0.5286657  0.93290848]

In [7]:
arr_random = np.random.randint(0, 100, 10)
print(arr_random)

[41 92 62 74 98 52 56 74 49 25]

#### Excercise 1:

In [8]:
l = []

for i in range(5):
    l.append(input("Ingrese un número: "))

np_arr = np.array(l)
print(np_arr)

['1' '1' '2' '' '4']

### Pandas

In [9]:
data = {
    "State": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "Year": [2000, 2001, 2002, 2000, 2001, 2002],
    "population": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

# Crear un DataFrame a partir del diccionario
df = pd.DataFrame(data)

In [10]:
print(df)

    State  Year  population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         3.6
3  Nevada  2000         2.4
4  Nevada  2001         2.9
5  Nevada  2002         3.2

In [11]:
df.head(6)

    State  Year  population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         3.6
3  Nevada  2000         2.4
4  Nevada  2001         2.9
5  Nevada  2002         3.2

In [12]:
df.tail(3)

    State  Year  population
3  Nevada  2000         2.4
4  Nevada  2001         2.9
5  Nevada  2002         3.2

In [13]:
data = {
    "State": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "Year": [2000, 2001, 2002, 2000, 2001, 2002],
    "population": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
idx = ["one", "two", "three", "four", "five", "six"]
df = pd.DataFrame(data, index = idx)
print(df)

        State  Year  population
one      Ohio  2000         1.5
two      Ohio  2001         1.7
three    Ohio  2002         3.6
four   Nevada  2000         2.4
five   Nevada  2001         2.9
six    Nevada  2002         3.2

In [14]:
df_csv = pd.read_csv(os.path.join(ROOT, "Datasets", "employees.csv"))
df_csv_copy = df_csv.copy()
df_csv.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,21-Jun-07,SH_CLERK,2600,124,50
1,199,Douglas,Grant,13-Jan-08,SH_CLERK,2600,124,50
2,200,Jennifer,Whalen,17-Sep-03,AD_ASST,4400,101,10
3,201,Michael,Hartstein,17-Feb-04,MK_MAN,13000,100,20
4,202,Pat,Fay,17-Aug-05,MK_REP,6000,201,20

In [15]:
df_csv.shape

(50, 8)

In [16]:
df_csv.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'HIRE_DATE', 'JOB_ID',
       'SALARY', 'MANAGER_ID', 'DEPARTMENT_ID'],
      dtype='str')

In [17]:
df_csv.index

RangeIndex(start=0, stop=50, step=1)

In [18]:
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EMPLOYEE_ID    50 non-null     int64
 1   FIRST_NAME     50 non-null     str
 2   LAST_NAME      50 non-null     str
 3   HIRE_DATE      50 non-null     str
 4   JOB_ID         50 non-null     str
 5   SALARY         50 non-null     int64
 6   MANAGER_ID     50 non-null     str
 7   DEPARTMENT_ID  50 non-null     int64
dtypes: int64(3), str(5)
memory usage: 3.3 KB

In [19]:
df_csv.nunique()

EMPLOYEE_ID      50
FIRST_NAME       45
LAST_NAME        50
HIRE_DATE        47
JOB_ID           17
SALARY           32
MANAGER_ID       14
DEPARTMENT_ID    10
dtype: int64

In [20]:
df_csv["DEPARTMENT_ID"].unique()

array([ 50,  10,  20,  40,  70, 110,  90,  60, 100,  30])

In [21]:
print(df_csv["SALARY"])

0      2600
1      2600
2      4400
3     13000
4      6000
5      6500
6     10000
7     12008
8      8300
9     24000
10    17000
11    17000
12     9000
13     6000
14     4800
15     4800
16     4200
17    12008
18     9000
19     8200
20     7700
21     7800
22     6900
23    11000
24     3100
25     2900
26     2800
27     2600
28     2500
29     8000
30     8200
31     7900
32     6500
33     5800
34     3200
35     2700
36     2400
37     2200
38     3300
39     2800
40     2500
41     2100
42     3300
43     2900
44     2400
45     2200
46     3600
47     3200
48     2700
49     2500
Name: SALARY, dtype: int64

In [22]:
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EMPLOYEE_ID    50 non-null     int64
 1   FIRST_NAME     50 non-null     str
 2   LAST_NAME      50 non-null     str
 3   HIRE_DATE      50 non-null     str
 4   JOB_ID         50 non-null     str
 5   SALARY         50 non-null     int64
 6   MANAGER_ID     50 non-null     str
 7   DEPARTMENT_ID  50 non-null     int64
dtypes: int64(3), str(5)
memory usage: 3.3 KB

In [23]:
df_csv.columns = ["id_empleado", "nombre", "apellido", "fecha de contratación", "id_trabajo", "salario", "id_manager", "id_departamento"]

In [24]:
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_empleado            50 non-null     int64
 1   nombre                 50 non-null     str
 2   apellido               50 non-null     str
 3   fecha de contratación  50 non-null     str
 4   id_trabajo             50 non-null     str
 5   salario                50 non-null     int64
 6   id_manager             50 non-null     str
 7   id_departamento        50 non-null     int64
dtypes: int64(3), str(5)
memory usage: 3.3 KB

In [25]:
df_csv.columns = ["EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "HIRE_DATE", "JOB_ID", "SALARY", "MANAGER_ID", "DEPARTMENT_ID"]

In [26]:
# Count the number of missing values in each column
df.isna().sum()

State         0
Year          0
population    0
dtype: int64

### Views

In [27]:
plt.figure(figsize = (10, 6))

plt.tight_layout()
plt.show()